# Stage 1: Build the React application
FROM node:20.11.1-slim AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Declare the build-time argument
ARG VITE_API_URL
# Set it as an environment variable so Vite can use it
ENV VITE_API_URL=$VITE_API_URL

RUN npm run build

# Stage 2: Serve the application with Nginx
FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]